general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
}

# Dim screen after 5 minutes
listener {
    timeout = 300
    on-timeout = hyprctl keyword decoration:dim_strength 0.5 && hyprctl keyword decoration:dim_inactive false && hyprctl keyword decoration:dim_around 0.5
    on-resume = hyprctl keyword decoration:dim_strength 0.0 && hyprctl keyword decoration:dim_around 0.0
}

# Turn off display after 10 minutes
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Lock screen after 20 minutes
listener {
    timeout = 1200
    on-timeout = loginctl lock-session
}

# Suspend after 30 minutes
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
